# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/shuha/OneDrive/Skrivebord/Kurser/3.Semester/3 Ugers Projekt/Zip filer/Spaceinvaders/Spaceinvaders.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0.xci
# IP: The module: 'hdmi_in_axi_gpio_led_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shuha/OneDrive/Skrivebord/Kurser/3.Semester/3 Ugers Projekt/Zip filer/Spaceinvaders/Spaceinvaders.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_in_axi_gpio_led_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shuha/OneDrive/Skrivebord/Kurser/3.Semester/3 Ugers Projekt/Zip filer/Spaceinvaders/Spaceinvaders.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_in_axi_gpio_led_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shuha/OneDrive/Skrivebord/Kurser/3.Semester/3 Ugers Projekt/Zip filer/Spaceinvaders/Spaceinvaders.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_in_axi_gpio_led_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/shuha/OneDrive/Skrivebord/Kurser/3.Semester/3 Ugers Projekt/Zip filer/Spaceinvaders/Spaceinvaders.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0.xci
# IP: The module: 'hdmi_in_axi_gpio_led_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shuha/OneDrive/Skrivebord/Kurser/3.Semester/3 Ugers Projekt/Zip filer/Spaceinvaders/Spaceinvaders.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_in_axi_gpio_led_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shuha/OneDrive/Skrivebord/Kurser/3.Semester/3 Ugers Projekt/Zip filer/Spaceinvaders/Spaceinvaders.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_in_axi_gpio_led_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shuha/OneDrive/Skrivebord/Kurser/3.Semester/3 Ugers Projekt/Zip filer/Spaceinvaders/Spaceinvaders.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_in_axi_gpio_led_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
