set_property SRC_FILE_INFO {cfile:c:/SpaceInvaders/SpaceInvaders.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_processing_system7_0_0/hdmi_in_processing_system7_0_0.xdc rfile:../../../SpaceInvaders.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_processing_system7_0_0/hdmi_in_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:hdmi_in_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/SpaceInvaders/SpaceInvaders.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc rfile:../../../SpaceInvaders.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:c:/SpaceInvaders/SpaceInvaders.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_v_tc_0_0/hdmi_in_v_tc_0_0_clocks.xdc rfile:../../../SpaceInvaders.srcs/sources_1/bd/hdmi_in/ip/hdmi_in_v_tc_0_0/hdmi_in_v_tc_0_0_clocks.xdc id:3 order:LATE scoped_inst:hdmi_in_i/v_tc_0/U0} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.21
set_property src_info {type:SCOPED_XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_2 2.43
set_property src_info {type:SCOPED_XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C11" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C10" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B9" [get_ports "MIO[51]"]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B13" [get_ports "MIO[50]"]
set_property src_info {type:SCOPED_XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C12" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B12" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B14" [get_ports "MIO[47]"]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D16" [get_ports "MIO[46]"]
set_property src_info {type:SCOPED_XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B15" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F13" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A9" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E12" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C17" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D14" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C18" [get_ports "MIO[39]"]
set_property src_info {type:SCOPED_XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E13" [get_ports "MIO[38]"]
set_property src_info {type:SCOPED_XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A10" [get_ports "MIO[37]"]
set_property src_info {type:SCOPED_XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A11" [get_ports "MIO[36]"]
set_property src_info {type:SCOPED_XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F12" [get_ports "MIO[35]"]
set_property src_info {type:SCOPED_XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A12" [get_ports "MIO[34]"]
set_property src_info {type:SCOPED_XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D15" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A14" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E16" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C15" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C13" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C16" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D13" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A15" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F15" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A16" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B17" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F14" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A17" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D10" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B18" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E14" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A19" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C8" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C5" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E8" [get_ports "MIO[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D9" [get_ports "MIO[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C6" [get_ports "MIO[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E9" [get_ports "MIO[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B5" [get_ports "MIO[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D5" [get_ports "MIO[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D8" [get_ports "MIO[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A5" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A6" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B7" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D6" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B8" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A7" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E6" [get_ports "MIO[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H5" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G5" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M5" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P4" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N5" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B4" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W5" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R2" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G2" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C2" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W4" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T2" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F2" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B2" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E3" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E2" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E1" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C1" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D1" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D3" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A4" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V3" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V2" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A2" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W3" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y2" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y4" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W1" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y3" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V1" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U3" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U2" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U4" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T4" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B3" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R1" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R3" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P3" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P1" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J1" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H1" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H2" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J3" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H3" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G3" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C3" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y1" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T1" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F1" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A1" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N1" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N3" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L2" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M2" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P5" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J5" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R4" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L5" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J4" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K1" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K4" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L4" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L1" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M4" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K3" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M3" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:621 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K2" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F4" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:629 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D4" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:633 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E4" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G4" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F5" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:645 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N2" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C7" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:652 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B10" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E7" [get_ports "PS_CLK"]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports {sws_tri_i[0]}]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports {sws_tri_i[1]}]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {sws_tri_i[2]}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports {sws_tri_i[3]}]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports {btns_tri_i[0]}]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports {btns_tri_i[1]}]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {btns_tri_i[2]}]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports {btns_tri_i[3]}]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {leds_tri_io[0]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {leds_tri_io[1]}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {leds_tri_io[2]}]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {leds_tri_io[3]}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T19 [get_ports FCLK_CLK2]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports {Mute_tri_io}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports BCLK]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports PBLRCLK]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports RECLRCLK]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports RECDAT_0]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports PBDATA]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports IIC_0_scl_io]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports IIC_0_sda_io]
set_property src_info {type:XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {PS2_Data}]
set_property src_info {type:XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {PS2_Clk}]
set_property src_info {type:XDC file:2 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports {vga_r[0]}]
set_property src_info {type:XDC file:2 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20 [get_ports {vga_r[1]}]
set_property src_info {type:XDC file:2 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports {vga_r[2]}]
set_property src_info {type:XDC file:2 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports {vga_r[3]}]
set_property src_info {type:XDC file:2 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19 [get_ports {vga_r[4]}]
set_property src_info {type:XDC file:2 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {vga_g[0]}]
set_property src_info {type:XDC file:2 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports {vga_g[1]}]
set_property src_info {type:XDC file:2 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L19 [get_ports {vga_g[2]}]
set_property src_info {type:XDC file:2 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports {vga_g[3]}]
set_property src_info {type:XDC file:2 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20 [get_ports {vga_g[4]}]
set_property src_info {type:XDC file:2 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports {vga_g[5]}]
set_property src_info {type:XDC file:2 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P20 [get_ports {vga_b[0]}]
set_property src_info {type:XDC file:2 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports {vga_b[1]}]
set_property src_info {type:XDC file:2 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19 [get_ports {vga_b[2]}]
set_property src_info {type:XDC file:2 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports {vga_b[3]}]
set_property src_info {type:XDC file:2 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19 [get_ports {vga_b[4]}]
set_property src_info {type:XDC file:2 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P19 [get_ports vga_hs]
set_property src_info {type:XDC file:2 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R19 [get_ports vga_vs]
set_property src_info {type:XDC file:2 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property FIXED_ROUTE {{ CLK_BUFG_BUFGCTRL0_O CLK_BUFG_CK_GCLK0  { CLK_BUFG_REBUF_R_CK_GCLK0_TOP  { CLK_HROW_CK_MUX_OUT_L8 CLK_HROW_CK_HCLK_OUT_L8 CLK_HROW_CK_BUFHCLK_L8 HCLK_LEAF_CLK_B_BOTL5 <23>GCLK_L_B11_WEST CLK_L0 CLBLM_L_CLK }  CLK_HROW_CK_MUX_OUT_R8 CLK_HROW_CK_HCLK_OUT_R8 CLK_HROW_CK_BUFHCLK_R8  { HCLK_LEAF_CLK_B_BOTL5  { <21>GCLK_L_B11_WEST CLK_L0 CLBLL_L_CLK }   { <23>GCLK_L_B11_WEST CLK_L1 CLBLL_LL_CLK }  <24>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <5>HCLK_LEAF_CLK_B_BOTL5  { <25>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <9>GCLK_L_B11_EAST  { CLK0 BRAM_FIFO36_CLKBWRCLKL }  CLK1 BRAM_FIFO36_CLKBWRCLKU }   { <14>GCLK_L_B11_EAST  { CLK0 BRAM_FIFO36_CLKBWRCLKL }  CLK1 BRAM_FIFO36_CLKBWRCLKU }   { <19>GCLK_L_B11_EAST  { CLK0 BRAM_FIFO36_CLKBWRCLKL }  CLK1 BRAM_FIFO36_CLKBWRCLKU }  <24>GCLK_L_B11_EAST  { CLK0 BRAM_FIFO36_CLKBWRCLKL }  CLK1 BRAM_FIFO36_CLKBWRCLKU }   { <4>HCLK_LEAF_CLK_B_BOTL5 <24>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <6>HCLK_LEAF_CLK_B_BOTL5 <25>GCLK_L_B11_WEST CLK_L1 CLBLL_LL_CLK }  <2>HCLK_LEAF_CLK_B_BOTL5 <14>GCLK_L_B11_WEST  { CLK_L0 BRAM_FIFO36_CLKBWRCLKL }  CLK_L1 BRAM_FIFO36_CLKBWRCLKU }  CLK_BUFG_REBUF_R_CK_GCLK0_BOT  { CLK_HROW_CK_MUX_OUT_L8 CLK_HROW_CK_HCLK_OUT_L8 CLK_HROW_CK_BUFHCLK_L8  { <8>HCLK_LEAF_CLK_B_BOTL5  { <4>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <13>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <15>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <8>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <12>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <16>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <18>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <21>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <22>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <23>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <24>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <5>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <6>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <7>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <14>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  <21>GCLK_L_B11_WEST CLK_L0 PSS0_CLK_B0_4 PSS1_CLK_B0_4 PS7_SAXIHP0ACLK }   { <7>HCLK_LEAF_CLK_B_BOTL5  { <12>GCLK_L_B11_WEST CLK_L0 CLBLL_L_CLK }   { <16>GCLK_L_B11_WEST CLK_L0 CLBLL_L_CLK }   { <2>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <4>GCLK_L_B11_WEST CLK_L1 CLBLL_LL_CLK }   { <6>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <15>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <16>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <17>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <20>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <24>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <5>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <6>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <7>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <13>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <14>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <15>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <18>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <19>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <21>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <22>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <23>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <24>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <5>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <7>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <8>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <11>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <12>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <13>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <14>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <18>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <21>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <22>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  <23>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <6>HCLK_LEAF_CLK_B_BOTL5  { <14>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <17>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <19>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <24>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <5>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <10>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <16>GCLK_L_B11_WEST  { CLK_L0 BRAM_FIFO18_REGCLKARDRCLK }  CLK_L1 BRAM_RAMB18_REGCLKARDRCLK }   { <17>GCLK_L_B11_WEST  { CLK_L0 BRAM_FIFO18_CLKARDCLK }  CLK_L1 BRAM_RAMB18_CLKARDCLK }   { <19>GCLK_L_B11_WEST  { CLK_L0 BRAM_FIFO18_CLKBWRCLK }  CLK_L1 BRAM_RAMB18_CLKBWRCLK }   { <6>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <7>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <8>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <9>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <11>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <12>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <13>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <15>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <16>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <18>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <20>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <21>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <22>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  <23>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <5>HCLK_LEAF_CLK_B_BOTL5  { <14>GCLK_L_B11_WEST CLK_L0 CLBLM_L_CLK }   { <6>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <18>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <19>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <20>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <21>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <7>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <9>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <10>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <11>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <12>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <13>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <15>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <16>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <22>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }  <23>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <4>HCLK_LEAF_CLK_B_BOTL5  { <4>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <8>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <9>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <18>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <21>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <23>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <2>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <3>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <4>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <5>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <6>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <7>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <8>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <9>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <10>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <11>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <12>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <13>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <14>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <17>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <22>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <2>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <3>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <5>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <6>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <10>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <11>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  <12>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <3>HCLK_LEAF_CLK_B_BOTL5  { <5>GCLK_L_B11_EAST CLK1 CLBLL_LL_CLK }   { <6>GCLK_L_B11_EAST CLK1 CLBLL_LL_CLK }   { <8>GCLK_L_B11_EAST CLK1 CLBLL_LL_CLK }   { <10>GCLK_L_B11_EAST CLK1 CLBLL_LL_CLK }   { <11>GCLK_L_B11_EAST CLK1 CLBLL_LL_CLK }   { <2>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <3>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <4>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }  <12>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <2>HCLK_LEAF_CLK_B_BOTL5  { GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <4>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <7>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <7>GCLK_L_B11_EAST CLK1 CLBLL_LL_CLK }   { <5>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <6>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <8>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <9>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }  <8>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <7>HCLK_LEAF_CLK_B_TOPL5  { GCLK_L_B11_WEST CLK_L0 CLBLL_L_CLK }   { <2>GCLK_L_B11_WEST CLK_L1 CLBLL_LL_CLK }  GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <4>HCLK_LEAF_CLK_B_TOPL5  { <18>GCLK_L_B11_WEST CLK_L0 CLBLM_L_CLK }   { <12>GCLK_L_B11_WEST CLK_L0 CLBLM_L_CLK }   { <11>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <8>GCLK_L_B11_WEST CLK_L0 CLBLM_L_CLK }   { <7>GCLK_L_B11_WEST CLK_L0 CLBLM_L_CLK }   { <6>GCLK_L_B11_WEST CLK_L0 CLBLM_L_CLK }   { <5>GCLK_L_B11_WEST CLK_L0 CLBLM_L_CLK }   { <4>GCLK_L_B11_WEST CLK_L0 CLBLM_L_CLK }   { <2>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <2>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <3>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <14>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <12>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <10>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <9>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <8>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <7>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <6>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <5>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <4>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  <3>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <3>HCLK_LEAF_CLK_B_TOPL5  { <2>GCLK_L_B11_EAST CLK0 CLBLL_L_CLK }   { <9>GCLK_L_B11_EAST CLK1 CLBLL_LL_CLK }   { <17>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <16>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <11>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <8>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <7>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <6>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <5>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <4>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }  <3>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <2>HCLK_LEAF_CLK_B_TOPL5  { <18>GCLK_L_B11_EAST CLK0 CLBLL_L_CLK }   { <15>GCLK_L_B11_EAST CLK0 CLBLL_L_CLK }   { <6>GCLK_L_B11_EAST CLK0 CLBLL_L_CLK }   { <2>GCLK_L_B11_EAST CLK0 CLBLL_L_CLK }   { GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <20>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <17>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <16>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <15>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <14>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <13>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <12>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <11>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <10>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <9>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <8>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <7>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <6>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <5>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <4>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <3>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <2>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <17>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <16>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <14>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <13>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <12>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <11>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <10>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <9>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <8>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <7>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <5>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <4>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }  <3>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }  HCLK_LEAF_CLK_B_TOPL5  { <4>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <16>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <15>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <14>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <13>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <12>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <11>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <10>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <9>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <8>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <7>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <6>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }  <5>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }  CLK_HROW_CK_MUX_OUT_R8 CLK_HROW_CK_HCLK_OUT_R8 CLK_HROW_CK_BUFHCLK_R8  { HCLK_LEAF_CLK_B_TOPL5  { <16>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <12>GCLK_L_B11_WEST CLK_L0 CLBLL_L_CLK }   { <18>GCLK_L_B11_WEST CLK_L1 CLBLL_LL_CLK }   { <7>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <16>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <15>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <14>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <13>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <11>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <10>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <9>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <8>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <7>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <15>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <14>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <13>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <12>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <11>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <10>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <9>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  <8>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <2>HCLK_LEAF_CLK_B_TOPL5  { <11>GCLK_L_B11_EAST CLK0 CLBLL_L_CLK }   { <25>GCLK_L_B11_EAST CLK1 CLBLL_LL_CLK }   { <17>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <16>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <15>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <14>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <13>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <12>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <10>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <9>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <8>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }  <7>GCLK_L_B11_EAST  { CLK0 CLBLL_L_CLK }  CLK1 CLBLL_LL_CLK }   { <3>HCLK_LEAF_CLK_B_TOPL5  { <20>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <18>GCLK_L_B11_WEST CLK_L0 CLBLM_L_CLK }   { <17>GCLK_L_B11_WEST CLK_L0 CLBLM_L_CLK }   { <8>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <11>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <16>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <15>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <14>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <13>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <12>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <11>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <10>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <9>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <8>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <7>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <18>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <16>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <15>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <14>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <13>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <12>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <10>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <9>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  <7>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <4>HCLK_LEAF_CLK_B_TOPL5  { <17>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <16>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <15>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  <8>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <5>HCLK_LEAF_CLK_B_TOPL5  { <22>GCLK_L_B11_WEST CLK_L0 CLBLM_L_CLK }   { <23>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <18>GCLK_L_B11_WEST CLK_L1 CLBLM_M_CLK }   { <19>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <17>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <16>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }   { <14>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }  <13>GCLK_L_B11_WEST  { CLK_L0 CLBLM_L_CLK }  CLK_L1 CLBLM_M_CLK }  <6>HCLK_LEAF_CLK_B_TOPL5  { <16>GCLK_L_B11_EAST CLK0 CLBLM_L_CLK }   { <13>GCLK_L_B11_WEST CLK_L0 CLBLL_L_CLK }   { <10>GCLK_L_B11_WEST CLK_L0 CLBLL_L_CLK }   { <25>GCLK_L_B11_EAST CLK1 CLBLM_M_CLK }   { <21>GCLK_L_B11_WEST CLK_L1 CLBLL_LL_CLK }   { <18>GCLK_L_B11_WEST CLK_L1 CLBLL_LL_CLK }   { <17>GCLK_L_B11_WEST CLK_L1 CLBLL_LL_CLK }   { <16>GCLK_L_B11_WEST CLK_L1 CLBLL_LL_CLK }   { <25>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <24>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <22>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <20>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <19>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <15>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <14>GCLK_L_B11_WEST  { CLK_L0 CLBLL_L_CLK }  CLK_L1 CLBLL_LL_CLK }   { <24>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <23>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <22>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <20>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }   { <19>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  <18>GCLK_L_B11_EAST  { CLK0 CLBLM_L_CLK }  CLK1 CLBLM_M_CLK }  } [get_nets hdmi_in_i/processing_system7_0/inst/FCLK_CLK1]
set_property src_info {type:SCOPED_XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins hdmi_in_i/v_tc_0/U0/clk]] -to [all_registers -clock [get_clocks -of_objects [get_pins hdmi_in_i/v_tc_0/U0/s_axi_aclk]]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins hdmi_in_i/v_tc_0/U0/clk]]]
set_property src_info {type:SCOPED_XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins hdmi_in_i/v_tc_0/U0/s_axi_aclk]] -to [all_registers -clock [get_clocks -of_objects [get_pins hdmi_in_i/v_tc_0/U0/clk]]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins hdmi_in_i/v_tc_0/U0/s_axi_aclk]]]
