# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/ZYBO_Master.xdc

# Block Designs: bd/hdmi_in/hdmi_in.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in || ORIG_REF_NAME==hdmi_in} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_axi_dynclk_0_0/hdmi_in_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_dynclk_0_0 || ORIG_REF_NAME==hdmi_in_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_axi_gpio_btn_0/hdmi_in_axi_gpio_btn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_btn_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_btn_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_led_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_led_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_axi_gpio_sw_0/hdmi_in_axi_gpio_sw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_sw_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_sw_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_axi_mem_intercon_0/hdmi_in_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_mem_intercon_0 || ORIG_REF_NAME==hdmi_in_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_axi_vdma_0_0/hdmi_in_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_in_axi_vdma_0_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_processing_system7_0_0/hdmi_in_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_processing_system7_0_0 || ORIG_REF_NAME==hdmi_in_processing_system7_0_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_processing_system7_0_axi_periph_0/hdmi_in_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==hdmi_in_processing_system7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_rgb2vga_0_0/hdmi_in_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_rgb2vga_0_0 || ORIG_REF_NAME==hdmi_in_rgb2vga_0_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_100M_0/hdmi_in_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==hdmi_in_rst_processing_system7_0_100M_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_150M_0/hdmi_in_rst_processing_system7_0_150M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==hdmi_in_rst_processing_system7_0_150M_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_v_axi4s_vid_out_0_0/hdmi_in_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_in_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_v_tc_0_0/hdmi_in_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_v_tc_0_0 || ORIG_REF_NAME==hdmi_in_v_tc_0_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_xlconcat_0_0/hdmi_in_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_xlconcat_0_0 || ORIG_REF_NAME==hdmi_in_xlconcat_0_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_xbar_1/hdmi_in_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_xbar_1 || ORIG_REF_NAME==hdmi_in_xbar_1} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_1/hdmi_in_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_1 || ORIG_REF_NAME==hdmi_in_auto_pc_1} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_s00_regslice_0/hdmi_in_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_s00_regslice_0 || ORIG_REF_NAME==hdmi_in_s00_regslice_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_auto_pc_0/hdmi_in_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_pc_0 || ORIG_REF_NAME==hdmi_in_auto_pc_0} -quiet] -quiet

# IP: bd/hdmi_in/ip/hdmi_in_auto_us_df_0/hdmi_in_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_in_auto_us_df_0 || ORIG_REF_NAME==hdmi_in_auto_us_df_0} -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_btn_0/hdmi_in_axi_gpio_btn_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_btn_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_btn_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_btn_0/hdmi_in_axi_gpio_btn_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_btn_0/hdmi_in_axi_gpio_btn_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_btn_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_btn_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_led_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_led_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_led_0/hdmi_in_axi_gpio_led_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_led_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_led_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_sw_0/hdmi_in_axi_gpio_sw_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_sw_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_sw_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_sw_0/hdmi_in_axi_gpio_sw_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_axi_gpio_sw_0/hdmi_in_axi_gpio_sw_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_gpio_sw_0 || ORIG_REF_NAME==hdmi_in_axi_gpio_sw_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_axi_vdma_0_0/hdmi_in_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_in_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_axi_vdma_0_0/hdmi_in_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_in_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_axi_vdma_0_0/hdmi_in_axi_vdma_0_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_processing_system7_0_0/hdmi_in_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_processing_system7_0_0 || ORIG_REF_NAME==hdmi_in_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_100M_0/hdmi_in_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==hdmi_in_rst_processing_system7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_100M_0/hdmi_in_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==hdmi_in_rst_processing_system7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_150M_0/hdmi_in_rst_processing_system7_0_150M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==hdmi_in_rst_processing_system7_0_150M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_rst_processing_system7_0_150M_0/hdmi_in_rst_processing_system7_0_150M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_rst_processing_system7_0_150M_0 || ORIG_REF_NAME==hdmi_in_rst_processing_system7_0_150M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_v_axi4s_vid_out_0_0/hdmi_in_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_in_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_v_tc_0_0/hdmi_in_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_v_tc_0_0 || ORIG_REF_NAME==hdmi_in_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_1/hdmi_in_auto_pc_1_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_s00_regslice_0/hdmi_in_s00_regslice_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_s00_regslice_0 || ORIG_REF_NAME==hdmi_in_s00_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_s00_regslice_0/hdmi_in_s00_regslice_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_pc_0/hdmi_in_auto_pc_0_ooc.xdc

# XDC: bd/hdmi_in/ip/hdmi_in_auto_us_df_0/hdmi_in_auto_us_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_in_auto_us_df_0 || ORIG_REF_NAME==hdmi_in_auto_us_df_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/hdmi_in/ip/hdmi_in_auto_us_df_0/hdmi_in_auto_us_df_0_ooc.xdc

# XDC: bd/hdmi_in/hdmi_in_ooc.xdc
